version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
    networks:
      - expense_network
    environment:
      - PASSWORD_DB=rabee123
      - NAME_DB=expense_tracker_db
      - USER_DB=postgres
 
  db:
    image: postgres:latest
    environment:
      - PASSWORD_DB=rabee123
      - NAME_DB=expense_tracker_db
      - USER_DB=postgres
    expose:
      - "5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
        - expense_network

networks:
  expense_network:
    driver: bridge

volumes:
  postgres_data: