version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    container_name: expense_web_1
    volumes:
      - .:/app
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    ports:
      - 8000:8000
    restart: always
    environment:
      - POSTGRES_PASSWORD=rabee123
      - POSTGRES_NAME=postgres
      - POSTGRES_DB=postgres
    depends_on:
      - db
    networks:
      - expense_network

 
  db:
    image: postgres:15
    container_name: db

    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=rabee123
      - POSTGRES_NAME=postgres
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5434:5432
    expose:
      - "5434"

    networks:
        - expense_network


  nginx:
    image: nginx
    build: ./nginx
    ports:
      - "9000:80"
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - web
    restart: always
    networks:
      expense_network:


networks:
  expense_network:
    driver: bridge

volumes:
  postgres_data:
  media_volume:
  static_volume: