version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
    networks:
      - expense_network

 
  db:
    image: postgres
    ports:
      - '5432:5432'    
    environment:
      - HOST_DB=db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
        - expense_network

networks:
  expense_network:
    driver: bridge

volumes:
  postgres_data: