version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: rabee123
      POSTGRES_DB: expense_tracker_db
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: