# Generated by Django 5.0.2 on 2024-06-24 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodeVerification',
            new_name='OTPCode',
        ),
    ]
