# Generated by Django 5.0.2 on 2024-06-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_busdget_savingsgoal_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoal',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
