# Generated by Django 5.0.2 on 2024-07-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_spendinglimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='currency',
            field=models.CharField(default='ل.س', max_length=100),
        ),
        migrations.AddField(
            model_name='spendinglimit',
            name='currency',
            field=models.CharField(default='ل.س', max_length=100),
        ),
    ]
