# Generated by Django 5.0.2 on 2024-07-07 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_savingsgoal_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoal',
            name='current',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
    ]
