# Generated by Django 5.0.2 on 2024-07-29 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_savingsgoal_currency_spendinglimit_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendinglimit',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.expensecategory', unique=True),
        ),
    ]
