# Generated by Django 5.0.2 on 2024-07-29 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_alter_spendinglimit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendinglimit',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.expensecategory'),
        ),
    ]
