# Generated by Django 5.0.2 on 2024-07-29 13:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_alter_spendinglimit_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spendinglimit',
            unique_together={('user', 'category')},
        ),
    ]
