# Generated by Django 5.0.2 on 2024-07-29 13:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0006_alter_spendinglimit_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spendinglimit',
            unique_together={('user', 'category', 'start_date', 'end_date')},
        ),
    ]
