# Generated by Django 5.0.2 on 2024-07-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0007_alter_spendinglimit_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spendinglimit',
            unique_together=set(),
        ),
    ]
