# Generated by Django 5.0.2 on 2024-08-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0010_remove_upcomingpayment_account_upcomingpayment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingpayment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
